-- Phase 5: Dimensional warehouse schema.
-- Run after the reconciled layer has been designed and validated.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS dw;

CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_value DATE UNIQUE,
    year_number INTEGER,
    quarter_number INTEGER CHECK (quarter_number IS NULL OR quarter_number BETWEEN 1 AND 4),
    month_number INTEGER CHECK (month_number IS NULL OR month_number BETWEEN 1 AND 12),
    month_name TEXT,
    week_of_year INTEGER CHECK (week_of_year IS NULL OR week_of_year BETWEEN 1 AND 53),
    day_of_month INTEGER CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31),
    iso_day_of_week INTEGER CHECK (iso_day_of_week IS NULL OR iso_day_of_week BETWEEN 1 AND 7),
    day_name TEXT,
    is_weekend BOOLEAN,
    season_name TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_time (
    time_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hour_number INTEGER UNIQUE CHECK (hour_number IS NULL OR hour_number BETWEEN 0 AND 23),
    hour_label TEXT,
    part_of_day TEXT,
    day_night_class TEXT,
    is_night_hour BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_calendar_event (
    calendar_event_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_value DATE UNIQUE,
    is_public_holiday BOOLEAN,
    holiday_name TEXT,
    holiday_type TEXT,
    is_holiday_eve BOOLEAN,
    is_post_holiday BOOLEAN,
    is_bridge_day BOOLEAN,
    is_long_weekend BOOLEAN,
    holiday_window TEXT,
    event_group TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_weather (
    weather_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_date DATE UNIQUE,
    weather_station TEXT,
    weather_station_name TEXT,
    condition_class TEXT,
    severity_score INTEGER CHECK (severity_score IS NULL OR severity_score >= 0),
    severity_label TEXT,
    avg_temperature_c NUMERIC(8, 2),
    max_temperature_c NUMERIC(8, 2),
    min_temperature_c NUMERIC(8, 2),
    precipitation_mm NUMERIC(10, 2),
    snow_mm NUMERIC(10, 2),
    snow_depth_mm NUMERIC(10, 2),
    avg_wind_speed_mps NUMERIC(10, 2),
    fastest_2min_wind_mps NUMERIC(10, 2),
    weather_flags JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_geography (
    geography_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geography_code TEXT NOT NULL UNIQUE,
    nta_id TEXT UNIQUE,
    nta_name TEXT,
    nta_type TEXT,
    nta_abbrev TEXT,
    cdta_id TEXT,
    cdta_name TEXT,
    borough_code TEXT,
    borough_name TEXT,
    county_fips TEXT,
    city_name TEXT,
    geography_level TEXT NOT NULL DEFAULT 'nta',
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    geom GEOMETRY(MULTIPOLYGON, 4326),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_station (
    station_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id TEXT NOT NULL UNIQUE,
    station_name TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    geom GEOMETRY(POINT, 4326),
    geography_key INTEGER NOT NULL REFERENCES dw.dim_geography (geography_key),
    borough_name TEXT,
    geo_assignment_status TEXT,
    observation_count BIGINT,
    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_user_type (
    user_type_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_type TEXT NOT NULL UNIQUE,
    rider_type_label TEXT,
    is_member BOOLEAN,
    is_casual BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.dim_rideable_type (
    rideable_type_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rideable_type TEXT NOT NULL UNIQUE,
    rideable_type_label TEXT,
    is_electric BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dw.fact_trip (
    fact_trip_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id TEXT NOT NULL UNIQUE,
    start_date_key INTEGER NOT NULL REFERENCES dw.dim_date (date_key),
    end_date_key INTEGER NOT NULL REFERENCES dw.dim_date (date_key),
    start_time_key INTEGER NOT NULL REFERENCES dw.dim_time (time_key),
    end_time_key INTEGER NOT NULL REFERENCES dw.dim_time (time_key),
    start_calendar_event_key INTEGER NOT NULL REFERENCES dw.dim_calendar_event (calendar_event_key),
    start_weather_key INTEGER NOT NULL REFERENCES dw.dim_weather (weather_key),
    start_station_key INTEGER NOT NULL REFERENCES dw.dim_station (station_key),
    end_station_key INTEGER NOT NULL REFERENCES dw.dim_station (station_key),
    start_geography_key INTEGER NOT NULL REFERENCES dw.dim_geography (geography_key),
    end_geography_key INTEGER NOT NULL REFERENCES dw.dim_geography (geography_key),
    user_type_key INTEGER NOT NULL REFERENCES dw.dim_user_type (user_type_key),
    rideable_type_key INTEGER NOT NULL REFERENCES dw.dim_rideable_type (rideable_type_key),
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0),
    duration_minutes NUMERIC(10, 2) NOT NULL CHECK (duration_minutes > 0),
    approximate_distance_km NUMERIC(10, 3) CHECK (approximate_distance_km IS NULL OR approximate_distance_km >= 0),
    trip_count INTEGER NOT NULL DEFAULT 1 CHECK (trip_count = 1),
    is_night_trip BOOLEAN NOT NULL,
    night_trip_count INTEGER NOT NULL CHECK (night_trip_count IN (0, 1)),
    member_trip_count INTEGER NOT NULL CHECK (member_trip_count IN (0, 1)),
    casual_trip_count INTEGER NOT NULL CHECK (casual_trip_count IN (0, 1)),
    same_station_trip_count INTEGER NOT NULL CHECK (same_station_trip_count IN (0, 1)),
    within_nta_trip_count INTEGER NOT NULL CHECK (within_nta_trip_count IN (0, 1)),
    cross_nta_same_borough_trip_count INTEGER NOT NULL CHECK (cross_nta_same_borough_trip_count IN (0, 1)),
    cross_borough_trip_count INTEGER NOT NULL CHECK (cross_borough_trip_count IN (0, 1)),
    outside_or_unknown_trip_count INTEGER NOT NULL CHECK (outside_or_unknown_trip_count IN (0, 1)),
    flow_direction TEXT NOT NULL CHECK (
        flow_direction IN (
            'same_station',
            'within_nta',
            'cross_nta_same_borough',
            'cross_borough',
            'outside_or_unknown'
        )
    ),
    source_file TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fact_trip_one_user_indicator CHECK (member_trip_count + casual_trip_count IN (0, 1)),
    CONSTRAINT fact_trip_one_flow_indicator CHECK (
        same_station_trip_count
        + within_nta_trip_count
        + cross_nta_same_borough_trip_count
        + cross_borough_trip_count
        + outside_or_unknown_trip_count = 1
    )
);

CREATE TABLE IF NOT EXISTS dw.fact_station_day_hour (
    fact_station_day_hour_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_key INTEGER NOT NULL REFERENCES dw.dim_station (station_key),
    date_key INTEGER NOT NULL REFERENCES dw.dim_date (date_key),
    time_key INTEGER NOT NULL REFERENCES dw.dim_time (time_key),
    calendar_event_key INTEGER NOT NULL REFERENCES dw.dim_calendar_event (calendar_event_key),
    weather_key INTEGER NOT NULL REFERENCES dw.dim_weather (weather_key),
    trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (trip_starts >= 0),
    trip_ends INTEGER NOT NULL DEFAULT 0 CHECK (trip_ends >= 0),
    net_flow_count INTEGER GENERATED ALWAYS AS (trip_ends - trip_starts) STORED,
    night_trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (night_trip_starts >= 0),
    member_trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (member_trip_starts >= 0),
    casual_trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (casual_trip_starts >= 0),
    electric_trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (electric_trip_starts >= 0),
    classic_trip_starts INTEGER NOT NULL DEFAULT 0 CHECK (classic_trip_starts >= 0),
    total_start_duration_seconds BIGINT NOT NULL DEFAULT 0 CHECK (total_start_duration_seconds >= 0),
    avg_start_duration_minutes NUMERIC(10, 2),
    total_start_distance_km NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (total_start_distance_km >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fact_station_day_hour UNIQUE (station_key, date_key, time_key)
);

CREATE INDEX IF NOT EXISTS idx_dw_dim_date_hierarchy
    ON dw.dim_date (year_number, season_name, quarter_number, month_number, week_of_year);

CREATE INDEX IF NOT EXISTS idx_dw_dim_time_part
    ON dw.dim_time (day_night_class, part_of_day, hour_number);

CREATE INDEX IF NOT EXISTS idx_dw_dim_calendar_event_window
    ON dw.dim_calendar_event (holiday_window, is_long_weekend, is_public_holiday);

CREATE INDEX IF NOT EXISTS idx_dw_dim_weather_condition
    ON dw.dim_weather (condition_class, severity_label);

CREATE INDEX IF NOT EXISTS idx_dw_dim_geography_hierarchy
    ON dw.dim_geography (city_name, borough_name, cdta_id, nta_id);

CREATE INDEX IF NOT EXISTS idx_dw_dim_geography_geom
    ON dw.dim_geography USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_dw_dim_station_geography
    ON dw.dim_station (geography_key, geo_assignment_status);

CREATE INDEX IF NOT EXISTS idx_dw_dim_station_geom
    ON dw.dim_station USING GIST (geom);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_start_date_time
    ON dw.fact_trip (start_date_key, start_time_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_end_date_time
    ON dw.fact_trip (end_date_key, end_time_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_start_station
    ON dw.fact_trip (start_station_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_end_station
    ON dw.fact_trip (end_station_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_start_geography
    ON dw.fact_trip (start_geography_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_end_geography
    ON dw.fact_trip (end_geography_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_weather_event
    ON dw.fact_trip (start_weather_key, start_calendar_event_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_user_rideable
    ON dw.fact_trip (user_type_key, rideable_type_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_flow_direction
    ON dw.fact_trip (flow_direction);

CREATE INDEX IF NOT EXISTS idx_dw_fact_trip_night
    ON dw.fact_trip (is_night_trip);

CREATE INDEX IF NOT EXISTS idx_dw_fact_station_day_hour_date_time
    ON dw.fact_station_day_hour (date_key, time_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_station_day_hour_station_date
    ON dw.fact_station_day_hour (station_key, date_key);

CREATE INDEX IF NOT EXISTS idx_dw_fact_station_day_hour_weather_event
    ON dw.fact_station_day_hour (weather_key, calendar_event_key);

COMMENT ON TABLE dw.dim_date IS 'Date hierarchy for roll-up from date to week, month, quarter, season, and year.';
COMMENT ON TABLE dw.dim_time IS 'Hour-level time hierarchy for part-of-day and night/day analysis.';
COMMENT ON TABLE dw.dim_calendar_event IS 'Date-scoped holiday and long-weekend context.';
COMMENT ON TABLE dw.dim_weather IS 'Daily NOAA weather context linked to trip start date.';
COMMENT ON TABLE dw.dim_geography IS 'NTA-level geography dimension with CDTA, borough, and city hierarchy.';
COMMENT ON TABLE dw.dim_station IS 'Citi Bike station dimension snowflaked to geography.';
COMMENT ON TABLE dw.dim_user_type IS 'Member and casual rider type dimension.';
COMMENT ON TABLE dw.dim_rideable_type IS 'Classic and electric rideable type dimension.';
COMMENT ON TABLE dw.fact_trip IS 'Ride-grain fact table sourced from reconciled accepted trips.';
COMMENT ON TABLE dw.fact_station_day_hour IS 'Station-day-hour aggregate fact for fast OLAP demo queries.';

